build:
    nodes:
        analysis:
            project_setup:
                override: true
            environment:
                php: 7.1

checks:
    php : true

filter:
    excluded_paths:
        - "tests/"
        # Everything in a root level "tests" directory will be excluded
    dependency_paths:
        - "vendor/"
        # Everything in a root level "vendor" directory will be excluded from analysis
        # but treated as a dependency

tools:
    external_code_coverage: 
        timeout: 120
