language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - .travis/downloads

before_install:
  - |
    if [ "x$REMOVE_QA" = "xyes" ]; then
      composer remove infection/infection friendsofphp/php-cs-fixer phpstan/phpstan phpstan/phpstan-phpunit phpstan/phpstan-strict-rules --dev --no-interaction $COMPOSER_ARGS;
    fi
  - |
    if [ "x$XDEBUG" != "xyes" ]; then
      phpenv config-rm xdebug.ini || true
    fi
  - |
    if [ "x$INSTALL_JASPER" == "xyes" ]; then
      .travis/build_javabridge_jasper_war.sh
      .travis/run_javabridge_jasper.sh
      sleep 5
      ls -la .travis/
      cat .travis/*.log
      cat .travis/*.pid
    fi

install:
  - |
    if [[ "x$DEPS" == "xlowest" ]]; then
      travis_retry composer -n update --prefer-dist --prefer-lowest --prefer-stable --no-interaction $COMPOSER_ARGS;
    else
      travis_retry composer -n update --prefer-dist --no-interaction $COMPOSER_ARGS;
    fi

  # Smoke test server install
  - composer install -d ./tests/server/expressive --ignore-platform-reqs

  # Create and populate the test database
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot
  - mysql -e "create database phpunit_soluble_test_db;" -uroot
  - zcat tests/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db
  - zcat tests/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db

script:
  - ./vendor/bin/phpunit -v -c .travis/phpunit.xml

jobs:
  allow_failures:
    - php: nightly
    - stage: No-leaks

  include:
    - stage: Tests
      php: 7.3
      env: XDEBUG=yes INSTALL_JASPER=yes REMOVE_QA=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        - bash <(curl -s https://codecov.io/bash)

    - stage: Tests
      php: 7.2
      env: INSTALL_JASPER=yes REMOVE_QA=yes

    - stage: Tests
      php: 7.1
      env: INSTALL_JASPER=yes REMOVE_QA=yes

    - stage: Tests
      php: 7.1
      env: INSTALL_JASPER=yes DEPS=lowest REMOVE_QA=yes
      script:
        - composer remove phpunit/phpunit
        - composer require --dev phpunit/phpunit
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml

    - stage: Tests
      php: nightly
      env: COMPOSER_ARGS=--ignore-platform-reqs REMOVE_QA=yes
      script:
        - ./vendor/bin/phpunit --testsuite unit -v -c .travis/phpunit.xml

    - stage: PHPStan and Code style
      php: 7.3
      env: XDEBUG=false INSTALL_JASPER=no REMOVE_QA=no
      script:
        - composer phpstan
        - composer cs-check

    - stage: Mutation (unit tests only)
      php: 7.3
      env: XDEBUG=yes INSTALL_JASPER=no
      script:
        - if [[ $INFECTION == true ]]; then ./vendor/bin/infection --configuration=.travis/infection.travis.json --test-framework=phpunit --min-msi=70 --min-covered-msi=75 --threads=4; fi

    - stage: No-leaks
      php: 7.3
      env: XDEBUG=yes INSTALL_JASPER=yes
      script:
        - composer require --dev roave/no-leaks
        - ./vendor/bin/roave-no-leaks



