language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 7.1
      env:
        - SEND_COVERAGE=true
        - CHECK=true
        - INFECTION=true
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  # -------------------------------------------------------------------------
  # Step 1: Regular composer install
  - composer install --no-interaction --ignore-platform-reqs
  - composer install-expressive-testapp

  #
  # -------------------------------------------------------------------------
  # Step 2: Create and populate the test database
  # -------------------------------------------------------------------------
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot
  - mysql -e "create database phpunit_soluble_test_db;" -uroot
  - zcat tests/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db
  - zcat tests/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db
  # -------------------------------------------------------------------------
  # Step 3: Create and launch the javabridge server
  #         with jasper report dependencies.
  # -------------------------------------------------------------------------
  # Step 3.1: Build a servlet (war) with jasper/mysql/javabridge...
  - .travis/build_javabridge_jasper_war.sh
  # Step 3.2: Run the servlet
  - .travis/run_javabridge_jasper.sh
  # Step 3.3: sleep a bit to let the server starts
  - sleep 5
  - ls -la .travis/
  # Step 3.4: some log for debugging travis in case
  - cat .travis/*.log
  - cat .travis/*.pid

script:
  - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
  - if [[ $CHECK == true ]]; then composer check; fi
  - if [[ $INFECTION == true ]]; then ./vendor/bin/infection --configuration=.travis/infection.travis.json --test-framework=phpunit --min-msi=80 --min-covered-msi=90 --threads=4; fi

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
