language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 7.1
      env:
        - EXECUTE_TEST_COVERALLS=true
        - SEND_COVERAGE=true

before_script:
  # Step 1: somme needed directories
  - mkdir -p build/logs
  - mkdir -p test/logs
  # Step 2: regular composer install
  - composer install
  # Step 3: Ensure a javabridge server is working
  # Step 3.1: Build a servlet (war) with jasper/mysql/javabridge...
  - .travis/build_javabridge_jasper_war.sh
  # Step 3.2: Run the servlet
  - .travis/run_javabridge_jasper.sh
  - ls -la .travis/
  - cat .travis/*.log
  - cat .travis/*.pid


    
script:
  - ./vendor/bin/phpunit -v -c .travis/phpunit.travis.xml --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - composer phpstan

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
